name: Maven Checkstyle

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main", "master"]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Checkstyle
        run: mvn -B checkstyle:check
